### ISSUE TITLE
Potential issue with how gorilla installs .nupkg

### ISSUE THREAD

**Issue by erikng** [1dustindavis/gorilla#59] opened 2019-02-01 13:57 UTC
When debugging another issue, I noticed when invoking chocolatey through PowerShell.

`The use of .nupkg or .nuspec in for package name or source is known to cause issues. Please use the package id from the nuspec `<id />` with `-s .` (for local folder where nupkg is found).`

I'm not sure what issues this could cause, but perhaps this needs to be fleshed out or better understood. Perhaps Gorilla will fail to install some packages.

**Comment by erikng** [comment] 2019-02-01 13:58
This might be a duplicate of: https://github.com/1dustindavis/gorilla/issues/54

**Comment by 1dustindavis** [comment] 2019-02-02 17:10
Duplicate of #54

**Closed** 2019-02-02 17:10 UTC
