### ISSUE TITLE
Middleware or Built-In Integration With Cloud Repo

### ISSUE THREAD

**Issue by gyamada619** [1dustindavis/gorilla#63] opened 2019-03-10 20:15 UTC
I cobbled together some code for a section of the `download` package that can connect to a Backblaze B2 bucket and grab code & packages from a gorilla repo inside said bucket. Feel free to integrate or use at your discretion @1dustindavis; I have no plans to implement it in our environment anymore since we decided to go with an on-prem server.

Code is [in a Gist over here](https://gist.github.com/gyamada619/4d445cf1cf71102d72eaa617e8127c52).

**Comment by 1dustindavis** [comment] 2019-03-17 21:09
Thanks Garrett! I am going to close this issue as a duplicate of #30, but the gist could be super helpful for understanding how to best add support generic middleware!

**Closed by 1dustindavis** 2019-03-17 21:09 UTC
Labels: after 1.0, enhancement
